"""Delivery repo scaffolding for Zero Operators.

Creates a standard ML project layout with Docker support in a target
delivery repository. Files are only written when they don't already exist,
making the operation safe to re-run.

The structure separates concerns into:
- ``configs/`` — YAML configuration (never hardcode in code)
- ``src/`` — source code by responsibility (data, model, engineering, inference, utils)
- ``experiments/`` — context trail (config snapshots, results, notes per experiment)
- ``notebooks/`` — human exploration (data/, model/, analysis/) + ZO auto-generated (phase/)
- ``tests/`` — unit tests (code correctness) + ML tests (oracle thresholds, benchmarks)
- ``docker/`` — containerisation (Dockerfile, compose, .dockerignore)
- ``reports/`` — agent-generated analysis and figures
"""

from __future__ import annotations

from pathlib import Path

from rich.console import Console

_AMBER = "bold #F0C040"
_DIM = "#8a6020"

console = Console()

# ---------------------------------------------------------------------------
# Directory layout
# ---------------------------------------------------------------------------

# Directories that are ZO-specific and always created (even in adaptive
# mode). These don't conflict with user code conventions — they're where
# agents drop configs, experiment trails, reports, phase notebooks, and
# containerisation files.
_META_DIRECTORIES: list[str] = [
    # Config
    "configs/data",
    "configs/model",
    "configs/training",
    "configs/experiment",
    # Experiment trail
    "experiments",
    # Reports (agent-generated)
    "reports/figures",
    # Auto-generated phase notebooks (ZO artefacts)
    "notebooks/phase",
    # Containerisation
    "docker",
]

# Directories that assume ZO's responsibility-based layout. Skipped in
# adaptive mode so existing repos keep their own conventions.
_STANDARD_DIRECTORIES: list[str] = [
    # Source code
    "src/data",
    "src/model",
    "src/engineering",
    "src/inference",
    "src/utils",
    # Data
    "data/raw",
    "data/processed",
    # Artifacts
    "models",
    # Human-authored notebooks
    "notebooks/data",
    "notebooks/model",
    "notebooks/analysis",
    # Tests — code correctness vs ML validation
    "tests/unit",
    "tests/ml",
    "tests/fixtures",
]

# Kept for backwards compatibility with existing callers / tests that
# reference ``_DIRECTORIES`` directly. ``standard`` mode uses both lists.
_DIRECTORIES: list[str] = _META_DIRECTORIES + _STANDARD_DIRECTORIES

# ---------------------------------------------------------------------------
# File templates — ``{project_name}`` is interpolated where it appears.
# Templates with shell ``${VAR}`` syntax are written verbatim.
# ---------------------------------------------------------------------------

_README_TEMPLATE = """\
# {project_name}

Generated by [Zero Operators](https://github.com/SamPlvs/zero-operators).

## Quick Start

```bash
# Build Docker container
cd docker && docker compose build && cd ..

# Run training
docker compose -f docker/docker-compose.yml run --rm gpu python -m src.engineering.trainer

# Run tests
docker compose -f docker/docker-compose.yml run --rm gpu python -m pytest tests/
```

## Structure

See `STRUCTURE.md` for the full directory reference.
"""

_STRUCTURE_TEMPLATE = """\
# {project_name} — Directory Reference

Agents and humans use this file to navigate the delivery repo.
Read the section you need — don't load everything.

## configs/
YAML configuration files. Agents edit these to change experiments.
- `configs/data/` — dataset paths, splits, preprocessing params
- `configs/model/` — architecture hyperparameters
- `configs/training/` — optimizer, LR schedule, epochs, batch size
- `configs/experiment/base.yaml` — master config composing the above

## src/
Source code organised by responsibility.
- `src/data/` — Dataset classes, transforms, DataLoader factory, splitting
- `src/model/` — Model zoo (architectures, heads, base classes)
- `src/engineering/` — Training loop, DDP/FSDP, tracking, checkpointing, evaluation
- `src/inference/` — Production inference, ONNX/TorchScript export, serving
- `src/utils/` — File I/O, plotting, logging, reproducibility helpers

## experiments/
Context trail for what was tried, results, and next steps.
- `experiments/README.md` — Index of experiments and current status
- `experiments/exp-NNN/config.yaml` — Frozen config snapshot
- `experiments/exp-NNN/results.json` — Metrics and timings
- `experiments/exp-NNN/notes.md` — What, why, outcome, next steps

## reports/
Agent-generated analysis (read-only for humans).
- `reports/figures/` — Plots, confusion matrices, training curves
- `reports/data_quality_report.md` — Phase 1 output
- `reports/training_report.md` — Phase 4 output
- `reports/analysis_report.md` — Phase 5 output
- `reports/model_card.md` — Phase 6 output
- `reports/validation_report.md` — Phase 6 output

## notebooks/
- `notebooks/data/` — Data exploration (human-authored)
- `notebooks/model/` — Architecture experiments (human-authored)
- `notebooks/analysis/` — Explainability, error analysis (human-authored)
- `notebooks/phase/` — ZO auto-generated per-phase notebooks

## tests/
- `tests/unit/` — Code correctness (does the code run?)
- `tests/ml/` — Oracle validation (does the model meet thresholds?)
- `tests/fixtures/` — Test data and mocks

## docker/
- `docker/Dockerfile` — Multi-stage build (pytorch → uv → deps → code)
- `docker/docker-compose.yml` — GPU service with volume mounts

## models/
Trained checkpoints (*.pt, *.onnx). Not source code.

## data/
- `data/raw/` — Original data (gitignored, downloaded at runtime)
- `data/processed/` — Cleaned, split, ready for training
"""

_EXPERIMENTS_README = """\
# Experiments

Index of experiments for this project. Agents update this file after each run.

| ID | Config | Status | Primary Metric | Notes |
|----|--------|--------|----------------|-------|
| — | — | No experiments yet | — | — |

## Current Direction

(To be filled by Lead Orchestrator after Phase 3)
"""

_PYPROJECT_TEMPLATE = """\
[project]
name = "{project_name}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8.0", "ruff>=0.4.0"]
"""

_BASE_CONFIG_TEMPLATE = """\
# Master experiment config — composes data, model, training configs.
# Agents edit this to define experiment parameters.
# Frozen snapshots saved to experiments/exp-NNN/config.yaml.

data:
  # dataset: configs/data/dataset.yaml
  # augmentation: configs/data/augmentation.yaml

model:
  # architecture: configs/model/architecture.yaml

training:
  # optimizer: configs/training/optimizer.yaml
  # trainer: configs/training/trainer.yaml
"""

_GITIGNORE_TEMPLATE = """\
__pycache__/
*.pyc
.env
*.pt
*.onnx
*.pkl
data/raw/
.venv/
.coverage
.pytest_cache/
*.egg-info/
dist/
build/
"""

_DOCKERIGNORE_TEMPLATE = """\
__pycache__/
.git/
.venv/
data/raw/
models/*.pt
*.egg-info/
"""

_DOCKERFILE_TEMPLATE = """\
# Zero Operators Delivery Container
# Agents customize BASE_IMAGE, system packages based on plan.md
ARG BASE_IMAGE=pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime
FROM ${BASE_IMAGE} AS base

ENV DEBIAN_FRONTEND=noninteractive

# Minimal system deps — agents add project-specific packages
RUN apt-get update && apt-get install -y --no-install-recommends \\
    git curl tmux htop sudo openssh-client \\
    && rm -rf /var/lib/apt/lists/*

# uv for fast Python dependency management
FROM base AS python-base
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
ENV UV_SYSTEM_PYTHON=1

# Dependencies — rebuilt only when pyproject.toml changes
FROM python-base AS deps
WORKDIR /project
COPY pyproject.toml uv.lock* ./
RUN uv sync --frozen 2>/dev/null || uv sync

# Runtime — rebuilt on code change (instant COPY)
FROM deps AS runtime
ARG USER_NAME=zo
ARG USER_ID=1000
RUN useradd -m -u ${USER_ID} -s /bin/bash ${USER_NAME} \\
    && echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
COPY . /project
RUN chown -R ${USER_NAME}:${USER_NAME} /project
USER ${USER_NAME}
WORKDIR /project
CMD ["/bin/bash"]
"""

_COMPOSE_TEMPLATE = """\
services:
  gpu:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BASE_IMAGE: pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime
        USER_NAME: ${USER:-zo}
        USER_ID: ${UID:-1000}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ../data:/project/data
      - ../models:/project/models
      - ../reports:/project/reports
      - ../notebooks:/project/notebooks
    ipc: host
    stdin_open: true
    tty: true
"""

_FILE_TEMPLATES: list[tuple[str, str]] = [
    ("README.md", _README_TEMPLATE),
    ("STRUCTURE.md", _STRUCTURE_TEMPLATE),
    ("pyproject.toml", _PYPROJECT_TEMPLATE),
    (".gitignore", _GITIGNORE_TEMPLATE),
    ("experiments/README.md", _EXPERIMENTS_README),
    ("configs/experiment/base.yaml", _BASE_CONFIG_TEMPLATE),
    ("docker/Dockerfile", _DOCKERFILE_TEMPLATE),
    ("docker/docker-compose.yml", _COMPOSE_TEMPLATE),
    ("docker/.dockerignore", _DOCKERIGNORE_TEMPLATE),
]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def scaffold_delivery(
    path: Path,
    project_name: str,
    *,
    overlay: bool = False,
    layout_mode: str = "standard",
) -> None:
    """Create the ZO project layout at *path*.

    Directories and files are created only when they don't already exist,
    so the function is safe to call repeatedly (idempotent).

    Args:
        path: Root directory for the delivery repo scaffold.
        project_name: Name interpolated into templates.
        overlay: When True, the operation is explicitly applying ZO
            structure to an existing repository. Affects logging, not
            which directories get created.
        layout_mode: Either ``"standard"`` or ``"adaptive"``.

            - ``"standard"`` (default) — creates the full ZO layout:
              ``configs/``, ``src/*``, ``data/``, ``experiments/``,
              ``reports/``, ``notebooks/*``, ``tests/*``, ``docker/``.
              Good for fresh projects and existing repos with no
              established code layout.

            - ``"adaptive"`` — creates only ZO meta-directories
              (``configs/``, ``experiments/``, ``reports/``,
              ``notebooks/phase/``, ``docker/``). Skips ``src/`` and
              ``data/`` so an existing repo's own code layout is left
              alone. Use for existing repos with established conventions
              (e.g. src-layout, django-style, flat layout). The caller
              is then responsible for writing a project-specific
              ``STRUCTURE.md`` and updating ``agent_working_dirs`` in
              the target file to point at the actual code paths.
    """
    if layout_mode not in {"standard", "adaptive"}:
        raise ValueError(
            f"layout_mode must be 'standard' or 'adaptive', "
            f"got {layout_mode!r}"
        )
    root = Path(path).resolve()
    mode = "overlay" if overlay else "scaffold"
    root.mkdir(parents=True, exist_ok=True)

    if layout_mode == "adaptive":
        dirs = _META_DIRECTORIES
    else:
        dirs = _META_DIRECTORIES + _STANDARD_DIRECTORIES

    dirs_created, dirs_preserved = _create_directories(
        root, dirs, overlay=overlay,
    )
    files_created, files_preserved = _create_template_files(
        root, project_name, overlay=overlay, layout_mode=layout_mode,
    )

    if overlay:
        console.print(
            f"\n[{_AMBER}]Overlay applied at:[/] {root} "
            f"([{_DIM}]{layout_mode}[/])\n"
            f"  [{_DIM}]dirs:[/] {dirs_created} added, "
            f"{dirs_preserved} preserved\n"
            f"  [{_DIM}]files:[/] {files_created} added, "
            f"{files_preserved} preserved"
        )
    else:
        console.print(
            f"\n[{_AMBER}]Delivery repo {mode}ed at:[/] {root} "
            f"([{_DIM}]{layout_mode}[/])"
        )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _create_directories(
    root: Path, dirs: list[str], *, overlay: bool = False,
) -> tuple[int, int]:
    """Create scaffold directories from *dirs* under *root*.

    Returns ``(created, preserved)`` counts. A ``.gitkeep`` placeholder is
    only written into directories that are truly empty — this avoids
    polluting existing code dirs when running in overlay mode.
    """
    created = 0
    preserved = 0
    for rel in dirs:
        d = root / rel
        if d.exists() and any(d.iterdir()):
            preserved += 1
            continue
        d.mkdir(parents=True, exist_ok=True)
        # .gitkeep only if still empty after mkdir (i.e. freshly created).
        if not any(d.iterdir()):
            gitkeep = d / ".gitkeep"
            if not gitkeep.exists():
                gitkeep.touch()
        created += 1
    if not overlay:
        console.print(f"[green]Created {created} directories[/]")
    return (created, preserved)


def _create_template_files(
    root: Path,
    project_name: str,
    *,
    overlay: bool = False,
    layout_mode: str = "standard",
) -> tuple[int, int]:
    """Write template files into *root*, skipping existing ones.

    In ``adaptive`` layout mode we omit ``README.md``, ``pyproject.toml``,
    and ``.gitignore`` — the existing repo almost certainly already has
    these and the templates would either be skipped as no-ops or, worse,
    misrepresent the project. We still write ``STRUCTURE.md`` (the Init
    Architect customises it afterwards), Docker files, and the base
    experiment config.

    Returns ``(created, preserved)`` counts.
    """
    if layout_mode == "adaptive":
        skip = {"README.md", "pyproject.toml", ".gitignore"}
        templates = [
            (p, t) for (p, t) in _FILE_TEMPLATES if p not in skip
        ]
    else:
        templates = _FILE_TEMPLATES

    created = 0
    preserved = 0
    for rel_path, template in templates:
        dest = root / rel_path
        if dest.exists():
            if not overlay:
                console.print(f"[{_DIM}]Already exists:[/] {rel_path}")
            preserved += 1
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        content = (
            template.format(project_name=project_name)
            if "{project_name}" in template
            else template
        )
        dest.write_text(content, encoding="utf-8")
        if not overlay:
            console.print(f"[green]Created:[/] {rel_path}")
        created += 1
    return (created, preserved)
