"""Delivery repo scaffolding for Zero Operators.

Creates a standard ML project layout with Docker support in a target
delivery repository. Files are only written when they don't already exist,
making the operation safe to re-run.
"""

from __future__ import annotations

from pathlib import Path

from rich.console import Console

# ZO brand colours (keep in sync with cli.py)
_AMBER = "bold #F0C040"
_DIM = "#8a6020"

console = Console()

# ---------------------------------------------------------------------------
# Directory layout
# ---------------------------------------------------------------------------

_DIRECTORIES: list[str] = [
    "data/raw",
    "data/processed",
    "src/models",
    "src/pipelines",
    "src/utils",
    "experiments",
    "models",
    "reports/figures",
    "notebooks",
    "tests/fixtures",
]

# ---------------------------------------------------------------------------
# File templates — each entry is (relative_path, content_template)
# Templates may contain ``{project_name}`` for string interpolation.
# ---------------------------------------------------------------------------

_README_TEMPLATE = """\
# {project_name}
Generated by Zero Operators.
"""

_PYPROJECT_TEMPLATE = """\
[project]
name = "{project_name}"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8.0", "ruff>=0.4.0"]
"""

_GITIGNORE_TEMPLATE = """\
__pycache__/
*.pyc
.env
*.pt
*.onnx
*.pkl
data/raw/
.venv/
.coverage
.pytest_cache/
*.egg-info/
dist/
build/
"""

_DOCKERIGNORE_TEMPLATE = """\
__pycache__/
.git/
.venv/
data/raw/
models/*.pt
*.egg-info/
"""

_DOCKERFILE_TEMPLATE = """\
# Zero Operators Delivery Container
# Agents customize BASE_IMAGE, system packages based on plan.md
ARG BASE_IMAGE=pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime
FROM ${BASE_IMAGE} AS base

ENV DEBIAN_FRONTEND=noninteractive

# Minimal system deps — agents add project-specific packages
RUN apt-get update && apt-get install -y --no-install-recommends \\
    git curl tmux htop sudo openssh-client \\
    && rm -rf /var/lib/apt/lists/*

# uv for fast Python dependency management
FROM base AS python-base
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
ENV UV_SYSTEM_PYTHON=1

# Dependencies — rebuilt only when pyproject.toml changes
FROM python-base AS deps
WORKDIR /project
COPY pyproject.toml uv.lock* ./
RUN uv sync --frozen 2>/dev/null || uv sync

# Runtime — rebuilt on code change (instant COPY)
FROM deps AS runtime
ARG USER_NAME=zo
ARG USER_ID=1000
RUN useradd -m -u ${USER_ID} -s /bin/bash ${USER_NAME} \\
    && echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
COPY . /project
RUN chown -R ${USER_NAME}:${USER_NAME} /project
USER ${USER_NAME}
WORKDIR /project
CMD ["/bin/bash"]
"""

_COMPOSE_TEMPLATE = """\
services:
  gpu:
    build:
      context: .
      args:
        BASE_IMAGE: pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime
        USER_NAME: ${USER:-zo}
        USER_ID: ${UID:-1000}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./data:/project/data
      - ./models:/project/models
      - ./reports:/project/reports
      - ./notebooks:/project/notebooks
    ipc: host
    stdin_open: true
    tty: true
"""

_FILE_TEMPLATES: list[tuple[str, str]] = [
    ("README.md", _README_TEMPLATE),
    ("pyproject.toml", _PYPROJECT_TEMPLATE),
    (".gitignore", _GITIGNORE_TEMPLATE),
    (".dockerignore", _DOCKERIGNORE_TEMPLATE),
    ("Dockerfile", _DOCKERFILE_TEMPLATE),
    ("docker-compose.yml", _COMPOSE_TEMPLATE),
]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def scaffold_delivery(path: Path, project_name: str) -> None:
    """Create the standard ML project layout at *path*.

    Directories and files are created only when they don't already exist,
    so the function is safe to call repeatedly.

    Args:
        path: Root directory for the delivery repo scaffold.
        project_name: Name interpolated into templates.
    """
    root = Path(path).resolve()
    root.mkdir(parents=True, exist_ok=True)

    _create_directories(root)
    _create_template_files(root, project_name)

    console.print(f"\n[{_AMBER}]Delivery repo scaffolded at:[/] {root}")


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _create_directories(root: Path) -> None:
    """Create all scaffold directories under *root*."""
    for rel in _DIRECTORIES:
        d = root / rel
        d.mkdir(parents=True, exist_ok=True)
        # Place a .gitkeep so empty dirs survive git
        gitkeep = d / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.touch()
    console.print(
        f"[green]Created {len(_DIRECTORIES)} directories[/]"
    )


def _create_template_files(root: Path, project_name: str) -> None:
    """Write template files into *root*, skipping existing ones."""
    for rel_path, template in _FILE_TEMPLATES:
        dest = root / rel_path
        if dest.exists():
            console.print(f"[{_DIM}]Already exists:[/] {rel_path}")
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        # Only interpolate templates that use {project_name};
        # others (Dockerfile, compose) contain shell ${VAR} syntax
        # that must not be interpreted by str.format().
        content = (
            template.format(project_name=project_name)
            if "{project_name}" in template
            else template
        )
        dest.write_text(content, encoding="utf-8")
        console.print(f"[green]Created:[/] {rel_path}")
